export const TX_LOADING = 'TX_LOADING';
export const TX_FAILED = 'TX_FAILED';
export const TX_SUCCESS = 'TX_SUCCESS';

export const SET_WEB3_INSTANCE = 'SET_WEB3_INSTANCE';
export const ADD_CONTRACT = 'ADD_CONTRACT';

export const REQUEST_CONNECTION = 'REQUEST_CONNECTION';
export const SET_NETWORK_ID = 'SET_NETWORK_ID';
export const SET_METAMASK_INSTALLED = 'SET_METAMASK_INSTALLED';
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT';
export const SET_CONNECTION = 'SET_CONNECTION';
export const SET_CONNECTED_TO_OPERATING_NETWORK = 'SET_CONNECTED_TO_OPERATING_NETWORK';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
export const ADD_TEST_CONTRACT = 'ADD_TEST_CONTRACT';

export const CHANGE_FORM_STATE = 'CHANGE_FORM_STATE';
export const form_states = {
    ERROR: 'ERROR',
    APPROVE: 'APPROVE',
    SWITCH_TO_CHAIN: 'SWITCH_TO_CHAIN',
    SEND_TX: 'SEND_TX'
}

export const SET_TOKEN_APPROVED = 'SET_TOKEN_APPROVED';
export const SET_CHAINS_MATCH = 'SET_CHAINS_MATCH';
export const SET_CUSTOM_TOKEN_SUPPORTED = 'SET_CUSTOM_TOKEN_SUPPORTED';
export const SET_TOKEN_IS_L2 = 'SET_TOKEN_IS_L2';

export const ADD_USER_TOKEN = 'ADD_USER_TOKEN';
export const REMOVE_USER_TOKEN = 'REMOVE_USER_TOKEN';

export const SET_SECTION = 'SET_SECTION';
